const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./src/routes.ts"];

const doc = {
  info: {
    version: "1.0.0",
    title: "Students API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3333",
  basePath: "/",
  schemes: ["http"],
  consumes: ["application/json"],
  produces: ["application/json"],
  definitions: {
    Student: {
      city: "Goiânia",
      course: "Engenharia de Software",
      courseType: "Graduação",
      courseGrau: "Bacharelado",
      shift: "Noturno",
      startYear: 2018,
      endYear: 2023,
      typeOfEntry: "ac",
      globalScore: 7.5,
      courseGlobalScore: 4.3,
      status: "",
    },
    AddStudent: {
      $city: "Goiânia",
      $course: "Engenharia de Software",
      $courseType: "Graduação",
      $courseGrau: "Bacharelado",
      $shift: "Noturno",
      $startYear: 2018,
      endYear: undefined,
      typeOfEntry: "ac",
      globalScore: 7.5,
      courseGlobalScore: 4.3,
      status: "",
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./index.ts");
});
